#!/usr/bin/env swift

import Foundation

enum GeneratorError: Error, CustomStringConvertible {
    case usage
    case malformedDictionary(String)

    var description: String {
        switch self {
        case .usage:
            return "usage: generate-aux-dictionary.swift <luna-pinyin.dict.yaml> <cangjie5.dict.yaml> <output>"
        case .malformedDictionary(let path):
            return "dictionary has no data section: \(path)"
        }
    }
}

struct DictionaryRow: Hashable {
    let text: String
    let code: String
    let weight: String?
}

func dictionaryRows(at path: String) throws -> [DictionaryRow] {
    let contents = try String(contentsOfFile: path, encoding: .utf8)
    let lines = contents.split(separator: "\n", omittingEmptySubsequences: false)
    guard let marker = lines.firstIndex(where: { $0.trimmingCharacters(in: .whitespaces) == "..." }) else {
        throw GeneratorError.malformedDictionary(path)
    }
    return lines[lines.index(after: marker)...].compactMap { line in
        if line.isEmpty || line.hasPrefix("#") {
            return nil
        }
        let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
        guard fields.count >= 2 else {
            return nil
        }
        let weight = fields.count >= 3 && !fields[2].isEmpty ? String(fields[2]) : nil
        return DictionaryRow(text: String(fields[0]), code: String(fields[1]), weight: weight)
    }
}

do {
    guard CommandLine.arguments.count == 4 else {
        throw GeneratorError.usage
    }
    let lunaPath = CommandLine.arguments[1]
    let cangjiePath = CommandLine.arguments[2]
    let outputPath = CommandLine.arguments[3]

    var stems: [String: Set<Character>] = [:]
    for row in try dictionaryRows(at: cangjiePath) {
        guard let stem = row.code.first, stem.isASCII, stem.isLetter else {
            continue
        }
        stems[row.text, default: []].insert(stem)
    }

    var generated = Set<DictionaryRow>()
    for row in try dictionaryRows(at: lunaPath) {
        guard let characterStems = stems[row.text], !row.code.contains(" ") else {
            continue
        }
        let pinyin = row.code.replacingOccurrences(of: "ü", with: "v")
        for stem in characterStems {
            generated.insert(DictionaryRow(text: row.text, code: pinyin + String(stem), weight: row.weight))
        }
    }

    let rows = generated.sorted {
        if $0.code != $1.code { return $0.code < $1.code }
        if $0.text != $1.text { return $0.text < $1.text }
        return ($0.weight ?? "") < ($1.weight ?? "")
    }
    let header = """
    # encoding: utf-8
    # Generated by Scripts/generate-aux-dictionary.swift.
    # Code = full pinyin + first Cangjie letter.
    # Do not edit this generated file directly.

    ---
    name: fengyu_aux
    version: "1.0.0"
    sort: by_weight
    use_preset_vocabulary: false
    ...

    """
    let body = rows.map { row in
        [row.text, row.code, row.weight].compactMap { $0 }.joined(separator: "\t")
    }.joined(separator: "\n")
    try (header + body + "\n").write(toFile: outputPath, atomically: true, encoding: .utf8)
    print("generatedRows=\(rows.count)")
} catch {
    fputs("generate-aux-dictionary: \(error)\n", stderr)
    exit(EXIT_FAILURE)
}
